# SPDX-License-Identifier: GPL-2.0

dtb-$(CONFIG_CAMERA_DREAM) += exynos8895-dreamlte_eur_open_05.dtb \
	exynos8895-dreamlte_eur_open_07.dtb \
	exynos8895-dreamlte_eur_open_08.dtb \
	exynos8895-dreamlte_eur_open_09.dtb \
	exynos8895-dreamlte_eur_open_10.dtb

dtb-$(CONFIG_CAMERA_DREAM2) += exynos8895-dream2lte_eur_open_07.dtb \
	exynos8895-dream2lte_eur_open_08.dtb \
	exynos8895-dream2lte_eur_open_09.dtb \
	exynos8895-dream2lte_eur_open_10.dtb

dtb-$(CONFIG_CAMERA_GREAT) += exynos8895-greatlte_eur_open_02.dtb \
	exynos8895-greatlte_eur_open_06.dtb

always            := $(dtb-y) $(dtbo-y)
clean-files       := *.dtb*
